version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean verify
  post_build:
    commands:
      - echo Build completed on `date`
      - rm -rf s3-tools && git clone --depth 1 https://github.com/loonwerks/s3-tools.git
      - export RELEASE_PKG_FILE=$(ls repository/target/com.rockwellcollins.atc.resolute.repository-*.zip)
      - echo "deploying $RELEASE_PKG_FILE to GitHub releases"
      - export SNAPSHOT_NUMBER=$(ls repository/target/repository/plugins/com.rockwellcollins.atc.resolute_*.jar | grep -o "[0-9]\\+\\.[0-9]\\+\\.[0-9]\\+\\.[0-9]\\{12\\}")
      - echo "deploying snapshot number $SNAPSHOT_NUMBER"`
      - python3 s3-tools/s3tools/DeployToP2CompositeRepository.py --path repository/target/repository --prefix p2/snapshots/resolute --child-name resolute_$SNAPSHOT_NUMBER --logging DEBUG
      - python3 s3-tools/s3tools/ManageSnapshots.py --prefix p2/snapshots/resolute --logging=DEBUG
artifacts:
  files:
    - repository/target/repository/**/*

