/*
 * Copyright (c) 2021, Collins Aerospace.
 * Developed with the sponsorship of Defense Advanced Research Projects Agency (DARPA).
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this data, 
 * including any software or models in source or binary form, as well as any drawings, specifications, 
 * and documentation (collectively "the Data"), to deal in the Data without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Data, and to permit persons to whom the Data is furnished to do so, 
 * subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or 
 * substantial portions of the Data.
 * 
 * THE DATA IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT 
 * LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
 * IN NO EVENT SHALL THE AUTHORS, SPONSORS, DEVELOPERS, CONTRIBUTORS, OR COPYRIGHT HOLDERS BE LIABLE 
 * FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE DATA OR THE USE OR OTHER DEALINGS IN THE DATA.
 *
 * Generated by Xtext version 2.25.0.
 */

package com.rockwellcollins.atc.resolute.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import com.rockwellcollins.atc.resolute.ide.contentassist.antlr.internal.InternalResoluteParser;
import com.rockwellcollins.atc.resolute.services.ResoluteGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class ResoluteParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(ResoluteGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, ResoluteGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getNamedElementAccess().getAlternatives(), "rule__NamedElement__Alternatives");
			builder.put(grammarAccess.getElementAccess().getAlternatives(), "rule__Element__Alternatives");
			builder.put(grammarAccess.getDefinitionAccess().getAlternatives(), "rule__Definition__Alternatives");
			builder.put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
			builder.put(grammarAccess.getBaseTypeAccess().getTypeAlternatives_0(), "rule__BaseType__TypeAlternatives_0");
			builder.put(grammarAccess.getArgAccess().getAlternatives(), "rule__Arg__Alternatives");
			builder.put(grammarAccess.getClaimTypeAccess().getAlternatives(), "rule__ClaimType__Alternatives");
			builder.put(grammarAccess.getDefinitionBodyAccess().getAlternatives(), "rule__DefinitionBody__Alternatives");
			builder.put(grammarAccess.getClaimAttributeAccess().getAlternatives(), "rule__ClaimAttribute__Alternatives");
			builder.put(grammarAccess.getClaimTextAccess().getAlternatives(), "rule__ClaimText__Alternatives");
			builder.put(grammarAccess.getClaimTextVarAccess().getAlternatives(), "rule__ClaimTextVar__Alternatives");
			builder.put(grammarAccess.getOrExprAccess().getAlternatives_1_0_0_1(), "rule__OrExpr__Alternatives_1_0_0_1");
			builder.put(grammarAccess.getAndExprAccess().getAlternatives_1_0_0_1(), "rule__AndExpr__Alternatives_1_0_0_1");
			builder.put(grammarAccess.getRelationalOpAccess().getAlternatives(), "rule__RelationalOp__Alternatives");
			builder.put(grammarAccess.getPlusExprAccess().getOpAlternatives_1_0_0_1_0(), "rule__PlusExpr__OpAlternatives_1_0_0_1_0");
			builder.put(grammarAccess.getTimesExprAccess().getOpAlternatives_1_0_0_1_0(), "rule__TimesExpr__OpAlternatives_1_0_0_1_0");
			builder.put(grammarAccess.getPrefixExprAccess().getAlternatives(), "rule__PrefixExpr__Alternatives");
			builder.put(grammarAccess.getPrefixExprAccess().getOpAlternatives_0_1_0(), "rule__PrefixExpr__OpAlternatives_0_1_0");
			builder.put(grammarAccess.getAtomicExprAccess().getAlternatives(), "rule__AtomicExpr__Alternatives");
			builder.put(grammarAccess.getAtomicExprAccess().getAlternatives_2_2(), "rule__AtomicExpr__Alternatives_2_2");
			builder.put(grammarAccess.getAtomicExprAccess().getQuantAlternatives_8_1_0(), "rule__AtomicExpr__QuantAlternatives_8_1_0");
			builder.put(grammarAccess.getAtomicExprAccess().getAlternatives_13_2(), "rule__AtomicExpr__Alternatives_13_2");
			builder.put(grammarAccess.getAtomicExprAccess().getAlternatives_14_2(), "rule__AtomicExpr__Alternatives_14_2");
			builder.put(grammarAccess.getBuiltInFnAccess().getAlternatives(), "rule__BuiltInFn__Alternatives");
			builder.put(grammarAccess.getLintStatementAccess().getAlternatives(), "rule__LintStatement__Alternatives");
			builder.put(grammarAccess.getAnalysisStatementAccess().getAlternatives(), "rule__AnalysisStatement__Alternatives");
			builder.put(grammarAccess.getAnalysisStatementAccess().getTagAlternatives_0_1_0(), "rule__AnalysisStatement__TagAlternatives_0_1_0");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getAlternatives_1(), "rule__ContainedPropertyAssociation__Alternatives_1");
			builder.put(grammarAccess.getPropertyAssociationAccess().getAlternatives_1(), "rule__PropertyAssociation__Alternatives_1");
			builder.put(grammarAccess.getPropertyExpressionAccess().getAlternatives(), "rule__PropertyExpression__Alternatives");
			builder.put(grammarAccess.getBooleanLiteralAccess().getAlternatives_1(), "rule__BooleanLiteral__Alternatives_1");
			builder.put(grammarAccess.getPlusMinusAccess().getAlternatives(), "rule__PlusMinus__Alternatives");
			builder.put(grammarAccess.getSignedIntAccess().getAlternatives_0(), "rule__SignedInt__Alternatives_0");
			builder.put(grammarAccess.getSignedRealAccess().getAlternatives_0(), "rule__SignedReal__Alternatives_0");
			builder.put(grammarAccess.getNumAltAccess().getAlternatives(), "rule__NumAlt__Alternatives");
			builder.put(grammarAccess.getResoluteLibraryAccess().getGroup(), "rule__ResoluteLibrary__Group__0");
			builder.put(grammarAccess.getTypeAccess().getGroup_0(), "rule__Type__Group_0__0");
			builder.put(grammarAccess.getTypeAccess().getGroup_1(), "rule__Type__Group_1__0");
			builder.put(grammarAccess.getTypeAccess().getGroup_2(), "rule__Type__Group_2__0");
			builder.put(grammarAccess.getTypeAccess().getGroup_2_1(), "rule__Type__Group_2_1__0");
			builder.put(grammarAccess.getTypeAccess().getGroup_3(), "rule__Type__Group_3__0");
			builder.put(grammarAccess.getArgAccess().getGroup_0(), "rule__Arg__Group_0__0");
			builder.put(grammarAccess.getArgAccess().getGroup_0_0(), "rule__Arg__Group_0_0__0");
			builder.put(grammarAccess.getArgAccess().getGroup_1(), "rule__Arg__Group_1__0");
			builder.put(grammarAccess.getConstantDefinitionAccess().getGroup(), "rule__ConstantDefinition__Group__0");
			builder.put(grammarAccess.getFunctionDefinitionAccess().getGroup(), "rule__FunctionDefinition__Group__0");
			builder.put(grammarAccess.getFunctionDefinitionAccess().getGroup_3(), "rule__FunctionDefinition__Group_3__0");
			builder.put(grammarAccess.getFunctionDefinitionAccess().getGroup_3_1(), "rule__FunctionDefinition__Group_3_1__0");
			builder.put(grammarAccess.getDefinitionBodyAccess().getGroup_0(), "rule__DefinitionBody__Group_0__0");
			builder.put(grammarAccess.getDefinitionBodyAccess().getGroup_1(), "rule__DefinitionBody__Group_1__0");
			builder.put(grammarAccess.getDefinitionBodyAccess().getGroup_1_2(), "rule__DefinitionBody__Group_1_2__0");
			builder.put(grammarAccess.getClaimContextAccess().getGroup(), "rule__ClaimContext__Group__0");
			builder.put(grammarAccess.getClaimJustificationAccess().getGroup(), "rule__ClaimJustification__Group__0");
			builder.put(grammarAccess.getClaimAssumptionAccess().getGroup(), "rule__ClaimAssumption__Group__0");
			builder.put(grammarAccess.getClaimStrategyAccess().getGroup(), "rule__ClaimStrategy__Group__0");
			builder.put(grammarAccess.getClaimTextAccess().getGroup_0(), "rule__ClaimText__Group_0__0");
			builder.put(grammarAccess.getClaimTextAccess().getGroup_1(), "rule__ClaimText__Group_1__0");
			builder.put(grammarAccess.getClaimTextAccess().getGroup_1_2(), "rule__ClaimText__Group_1_2__0");
			builder.put(grammarAccess.getImpliesExprAccess().getGroup(), "rule__ImpliesExpr__Group__0");
			builder.put(grammarAccess.getImpliesExprAccess().getGroup_1(), "rule__ImpliesExpr__Group_1__0");
			builder.put(grammarAccess.getImpliesExprAccess().getGroup_1_0(), "rule__ImpliesExpr__Group_1_0__0");
			builder.put(grammarAccess.getImpliesExprAccess().getGroup_1_0_0(), "rule__ImpliesExpr__Group_1_0_0__0");
			builder.put(grammarAccess.getOrExprAccess().getGroup(), "rule__OrExpr__Group__0");
			builder.put(grammarAccess.getOrExprAccess().getGroup_1(), "rule__OrExpr__Group_1__0");
			builder.put(grammarAccess.getOrExprAccess().getGroup_1_0(), "rule__OrExpr__Group_1_0__0");
			builder.put(grammarAccess.getOrExprAccess().getGroup_1_0_0(), "rule__OrExpr__Group_1_0_0__0");
			builder.put(grammarAccess.getAndExprAccess().getGroup(), "rule__AndExpr__Group__0");
			builder.put(grammarAccess.getAndExprAccess().getGroup_1(), "rule__AndExpr__Group_1__0");
			builder.put(grammarAccess.getAndExprAccess().getGroup_1_0(), "rule__AndExpr__Group_1_0__0");
			builder.put(grammarAccess.getAndExprAccess().getGroup_1_0_0(), "rule__AndExpr__Group_1_0_0__0");
			builder.put(grammarAccess.getInstanceOfExprAccess().getGroup(), "rule__InstanceOfExpr__Group__0");
			builder.put(grammarAccess.getInstanceOfExprAccess().getGroup_1(), "rule__InstanceOfExpr__Group_1__0");
			builder.put(grammarAccess.getInstanceOfExprAccess().getGroup_1_0(), "rule__InstanceOfExpr__Group_1_0__0");
			builder.put(grammarAccess.getInstanceOfExprAccess().getGroup_1_0_0(), "rule__InstanceOfExpr__Group_1_0_0__0");
			builder.put(grammarAccess.getRelationalExprAccess().getGroup(), "rule__RelationalExpr__Group__0");
			builder.put(grammarAccess.getRelationalExprAccess().getGroup_1(), "rule__RelationalExpr__Group_1__0");
			builder.put(grammarAccess.getRelationalExprAccess().getGroup_1_0(), "rule__RelationalExpr__Group_1_0__0");
			builder.put(grammarAccess.getRelationalExprAccess().getGroup_1_0_0(), "rule__RelationalExpr__Group_1_0_0__0");
			builder.put(grammarAccess.getPlusExprAccess().getGroup(), "rule__PlusExpr__Group__0");
			builder.put(grammarAccess.getPlusExprAccess().getGroup_1(), "rule__PlusExpr__Group_1__0");
			builder.put(grammarAccess.getPlusExprAccess().getGroup_1_0(), "rule__PlusExpr__Group_1_0__0");
			builder.put(grammarAccess.getPlusExprAccess().getGroup_1_0_0(), "rule__PlusExpr__Group_1_0_0__0");
			builder.put(grammarAccess.getTimesExprAccess().getGroup(), "rule__TimesExpr__Group__0");
			builder.put(grammarAccess.getTimesExprAccess().getGroup_1(), "rule__TimesExpr__Group_1__0");
			builder.put(grammarAccess.getTimesExprAccess().getGroup_1_0(), "rule__TimesExpr__Group_1_0__0");
			builder.put(grammarAccess.getTimesExprAccess().getGroup_1_0_0(), "rule__TimesExpr__Group_1_0_0__0");
			builder.put(grammarAccess.getExpExprAccess().getGroup(), "rule__ExpExpr__Group__0");
			builder.put(grammarAccess.getExpExprAccess().getGroup_1(), "rule__ExpExpr__Group_1__0");
			builder.put(grammarAccess.getExpExprAccess().getGroup_1_0(), "rule__ExpExpr__Group_1_0__0");
			builder.put(grammarAccess.getExpExprAccess().getGroup_1_0_0(), "rule__ExpExpr__Group_1_0_0__0");
			builder.put(grammarAccess.getPrefixExprAccess().getGroup_0(), "rule__PrefixExpr__Group_0__0");
			builder.put(grammarAccess.getPrefixExprAccess().getGroup_1(), "rule__PrefixExpr__Group_1__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_0(), "rule__AtomicExpr__Group_0__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_1(), "rule__AtomicExpr__Group_1__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_1_2(), "rule__AtomicExpr__Group_1_2__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_2(), "rule__AtomicExpr__Group_2__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_2_2_1(), "rule__AtomicExpr__Group_2_2_1__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_3(), "rule__AtomicExpr__Group_3__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_4(), "rule__AtomicExpr__Group_4__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_5(), "rule__AtomicExpr__Group_5__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_6(), "rule__AtomicExpr__Group_6__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_7(), "rule__AtomicExpr__Group_7__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_8(), "rule__AtomicExpr__Group_8__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_8_2(), "rule__AtomicExpr__Group_8_2__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_9(), "rule__AtomicExpr__Group_9__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_9_0(), "rule__AtomicExpr__Group_9_0__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_9_0_5(), "rule__AtomicExpr__Group_9_0_5__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_9_0_5_1(), "rule__AtomicExpr__Group_9_0_5_1__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_10(), "rule__AtomicExpr__Group_10__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_10_3(), "rule__AtomicExpr__Group_10_3__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_10_3_1(), "rule__AtomicExpr__Group_10_3_1__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_11(), "rule__AtomicExpr__Group_11__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_11_3(), "rule__AtomicExpr__Group_11_3__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_11_3_1(), "rule__AtomicExpr__Group_11_3_1__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_12(), "rule__AtomicExpr__Group_12__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_13(), "rule__AtomicExpr__Group_13__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_13_2_0(), "rule__AtomicExpr__Group_13_2_0__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_13_2_0_2(), "rule__AtomicExpr__Group_13_2_0_2__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_13_2_0_3(), "rule__AtomicExpr__Group_13_2_0_3__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_13_2_1(), "rule__AtomicExpr__Group_13_2_1__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_13_2_1_1(), "rule__AtomicExpr__Group_13_2_1_1__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_14(), "rule__AtomicExpr__Group_14__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_14_2_0(), "rule__AtomicExpr__Group_14_2_0__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_14_2_0_2(), "rule__AtomicExpr__Group_14_2_0_2__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_14_2_0_3(), "rule__AtomicExpr__Group_14_2_0_3__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_14_2_1(), "rule__AtomicExpr__Group_14_2_1__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_14_2_1_1(), "rule__AtomicExpr__Group_14_2_1_1__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_15(), "rule__AtomicExpr__Group_15__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_16(), "rule__AtomicExpr__Group_16__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_17(), "rule__AtomicExpr__Group_17__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_18(), "rule__AtomicExpr__Group_18__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_19(), "rule__AtomicExpr__Group_19__0");
			builder.put(grammarAccess.getAtomicExprAccess().getGroup_20(), "rule__AtomicExpr__Group_20__0");
			builder.put(grammarAccess.getLetBindingAccess().getGroup(), "rule__LetBinding__Group__0");
			builder.put(grammarAccess.getRealTermAccess().getGroup(), "rule__RealTerm__Group__0");
			builder.put(grammarAccess.getIntegerTermAccess().getGroup(), "rule__IntegerTerm__Group__0");
			builder.put(grammarAccess.getResoluteSubclauseAccess().getGroup(), "rule__ResoluteSubclause__Group__0");
			builder.put(grammarAccess.getNestedDotIDAccess().getGroup(), "rule__NestedDotID__Group__0");
			builder.put(grammarAccess.getNestedDotIDAccess().getGroup_1(), "rule__NestedDotID__Group_1__0");
			builder.put(grammarAccess.getLintStatementAccess().getGroup_0(), "rule__LintStatement__Group_0__0");
			builder.put(grammarAccess.getLintStatementAccess().getGroup_1(), "rule__LintStatement__Group_1__0");
			builder.put(grammarAccess.getLintStatementAccess().getGroup_2(), "rule__LintStatement__Group_2__0");
			builder.put(grammarAccess.getRulesetAccess().getGroup(), "rule__Ruleset__Group__0");
			builder.put(grammarAccess.getRulesetBodyAccess().getGroup(), "rule__RulesetBody__Group__0");
			builder.put(grammarAccess.getAnalysisStatementAccess().getGroup_0(), "rule__AnalysisStatement__Group_0__0");
			builder.put(grammarAccess.getAnalysisStatementAccess().getGroup_1(), "rule__AnalysisStatement__Group_1__0");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getGroup(), "rule__ContainedPropertyAssociation__Group__0");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getGroup_3(), "rule__ContainedPropertyAssociation__Group_3__0");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getGroup_3_1(), "rule__ContainedPropertyAssociation__Group_3_1__0");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getGroup_4(), "rule__ContainedPropertyAssociation__Group_4__0");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getGroup_4_2(), "rule__ContainedPropertyAssociation__Group_4_2__0");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getGroup_5(), "rule__ContainedPropertyAssociation__Group_5__0");
			builder.put(grammarAccess.getPropertyAssociationAccess().getGroup(), "rule__PropertyAssociation__Group__0");
			builder.put(grammarAccess.getPropertyAssociationAccess().getGroup_3(), "rule__PropertyAssociation__Group_3__0");
			builder.put(grammarAccess.getPropertyAssociationAccess().getGroup_3_1(), "rule__PropertyAssociation__Group_3_1__0");
			builder.put(grammarAccess.getPropertyAssociationAccess().getGroup_4(), "rule__PropertyAssociation__Group_4__0");
			builder.put(grammarAccess.getBasicPropertyAssociationAccess().getGroup(), "rule__BasicPropertyAssociation__Group__0");
			builder.put(grammarAccess.getModalPropertyValueAccess().getGroup(), "rule__ModalPropertyValue__Group__0");
			builder.put(grammarAccess.getModalPropertyValueAccess().getGroup_4(), "rule__ModalPropertyValue__Group_4__0");
			builder.put(grammarAccess.getOptionalModalPropertyValueAccess().getGroup(), "rule__OptionalModalPropertyValue__Group__0");
			builder.put(grammarAccess.getOptionalModalPropertyValueAccess().getGroup_1(), "rule__OptionalModalPropertyValue__Group_1__0");
			builder.put(grammarAccess.getOptionalModalPropertyValueAccess().getGroup_1_3(), "rule__OptionalModalPropertyValue__Group_1_3__0");
			builder.put(grammarAccess.getBooleanLiteralAccess().getGroup(), "rule__BooleanLiteral__Group__0");
			builder.put(grammarAccess.getReferenceTermAccess().getGroup(), "rule__ReferenceTerm__Group__0");
			builder.put(grammarAccess.getRecordTermAccess().getGroup(), "rule__RecordTerm__Group__0");
			builder.put(grammarAccess.getOldRecordTermAccess().getGroup(), "rule__OldRecordTerm__Group__0");
			builder.put(grammarAccess.getComputedTermAccess().getGroup(), "rule__ComputedTerm__Group__0");
			builder.put(grammarAccess.getComponentClassifierTermAccess().getGroup(), "rule__ComponentClassifierTerm__Group__0");
			builder.put(grammarAccess.getListTermAccess().getGroup(), "rule__ListTerm__Group__0");
			builder.put(grammarAccess.getListTermAccess().getGroup_2(), "rule__ListTerm__Group_2__0");
			builder.put(grammarAccess.getListTermAccess().getGroup_2_1(), "rule__ListTerm__Group_2_1__0");
			builder.put(grammarAccess.getFieldPropertyAssociationAccess().getGroup(), "rule__FieldPropertyAssociation__Group__0");
			builder.put(grammarAccess.getContainmentPathElementAccess().getGroup(), "rule__ContainmentPathElement__Group__0");
			builder.put(grammarAccess.getContainmentPathElementAccess().getGroup_0(), "rule__ContainmentPathElement__Group_0__0");
			builder.put(grammarAccess.getContainmentPathElementAccess().getGroup_1(), "rule__ContainmentPathElement__Group_1__0");
			builder.put(grammarAccess.getANNEXREFAccess().getGroup(), "rule__ANNEXREF__Group__0");
			builder.put(grammarAccess.getArrayRangeAccess().getGroup(), "rule__ArrayRange__Group__0");
			builder.put(grammarAccess.getArrayRangeAccess().getGroup_3(), "rule__ArrayRange__Group_3__0");
			builder.put(grammarAccess.getSignedConstantAccess().getGroup(), "rule__SignedConstant__Group__0");
			builder.put(grammarAccess.getSignedIntAccess().getGroup(), "rule__SignedInt__Group__0");
			builder.put(grammarAccess.getSignedRealAccess().getGroup(), "rule__SignedReal__Group__0");
			builder.put(grammarAccess.getNumericRangeTermAccess().getGroup(), "rule__NumericRangeTerm__Group__0");
			builder.put(grammarAccess.getNumericRangeTermAccess().getGroup_3(), "rule__NumericRangeTerm__Group_3__0");
			builder.put(grammarAccess.getAppliesToKeywordsAccess().getGroup(), "rule__AppliesToKeywords__Group__0");
			builder.put(grammarAccess.getInBindingKeywordsAccess().getGroup(), "rule__InBindingKeywords__Group__0");
			builder.put(grammarAccess.getInModesKeywordsAccess().getGroup(), "rule__InModesKeywords__Group__0");
			builder.put(grammarAccess.getQCLREFAccess().getGroup(), "rule__QCLREF__Group__0");
			builder.put(grammarAccess.getQPREFAccess().getGroup(), "rule__QPREF__Group__0");
			builder.put(grammarAccess.getQPREFAccess().getGroup_1(), "rule__QPREF__Group_1__0");
			builder.put(grammarAccess.getQCREFAccess().getGroup(), "rule__QCREF__Group__0");
			builder.put(grammarAccess.getQCREFAccess().getGroup_0(), "rule__QCREF__Group_0__0");
			builder.put(grammarAccess.getQCREFAccess().getGroup_2(), "rule__QCREF__Group_2__0");
			builder.put(grammarAccess.getResoluteLibraryAccess().getDefinitionsAssignment_1(), "rule__ResoluteLibrary__DefinitionsAssignment_1");
			builder.put(grammarAccess.getTypeAccess().getTypeAssignment_0_2(), "rule__Type__TypeAssignment_0_2");
			builder.put(grammarAccess.getTypeAccess().getTypeAssignment_1_2(), "rule__Type__TypeAssignment_1_2");
			builder.put(grammarAccess.getTypeAccess().getParamTypeAssignment_2_1_1(), "rule__Type__ParamTypeAssignment_2_1_1");
			builder.put(grammarAccess.getTypeAccess().getLibNameAssignment_3_1(), "rule__Type__LibNameAssignment_3_1");
			builder.put(grammarAccess.getTypeAccess().getFnTypeAssignment_3_3(), "rule__Type__FnTypeAssignment_3_3");
			builder.put(grammarAccess.getBaseTypeAccess().getTypeAssignment(), "rule__BaseType__TypeAssignment");
			builder.put(grammarAccess.getArgAccess().getNameAssignment_0_0_0(), "rule__Arg__NameAssignment_0_0_0");
			builder.put(grammarAccess.getArgAccess().getTypeAssignment_0_0_2(), "rule__Arg__TypeAssignment_0_0_2");
			builder.put(grammarAccess.getArgAccess().getNameAssignment_1_1(), "rule__Arg__NameAssignment_1_1");
			builder.put(grammarAccess.getArgAccess().getExprAssignment_1_3(), "rule__Arg__ExprAssignment_1_3");
			builder.put(grammarAccess.getConstantDefinitionAccess().getNameAssignment_0(), "rule__ConstantDefinition__NameAssignment_0");
			builder.put(grammarAccess.getConstantDefinitionAccess().getTypeAssignment_2(), "rule__ConstantDefinition__TypeAssignment_2");
			builder.put(grammarAccess.getConstantDefinitionAccess().getExprAssignment_4(), "rule__ConstantDefinition__ExprAssignment_4");
			builder.put(grammarAccess.getFunctionDefinitionAccess().getClaimTypeAssignment_0(), "rule__FunctionDefinition__ClaimTypeAssignment_0");
			builder.put(grammarAccess.getFunctionDefinitionAccess().getNameAssignment_1(), "rule__FunctionDefinition__NameAssignment_1");
			builder.put(grammarAccess.getFunctionDefinitionAccess().getArgsAssignment_3_0(), "rule__FunctionDefinition__ArgsAssignment_3_0");
			builder.put(grammarAccess.getFunctionDefinitionAccess().getArgsAssignment_3_1_1(), "rule__FunctionDefinition__ArgsAssignment_3_1_1");
			builder.put(grammarAccess.getFunctionDefinitionAccess().getBodyAssignment_5(), "rule__FunctionDefinition__BodyAssignment_5");
			builder.put(grammarAccess.getDefinitionBodyAccess().getTypeAssignment_0_2(), "rule__DefinitionBody__TypeAssignment_0_2");
			builder.put(grammarAccess.getDefinitionBodyAccess().getExprAssignment_0_4(), "rule__DefinitionBody__ExprAssignment_0_4");
			builder.put(grammarAccess.getDefinitionBodyAccess().getClaimAssignment_1_2_1(), "rule__DefinitionBody__ClaimAssignment_1_2_1");
			builder.put(grammarAccess.getDefinitionBodyAccess().getAttributesAssignment_1_3(), "rule__DefinitionBody__AttributesAssignment_1_3");
			builder.put(grammarAccess.getDefinitionBodyAccess().getExprAssignment_1_4(), "rule__DefinitionBody__ExprAssignment_1_4");
			builder.put(grammarAccess.getClaimContextAccess().getNameAssignment_1(), "rule__ClaimContext__NameAssignment_1");
			builder.put(grammarAccess.getClaimContextAccess().getExprAssignment_3(), "rule__ClaimContext__ExprAssignment_3");
			builder.put(grammarAccess.getClaimJustificationAccess().getNameAssignment_1(), "rule__ClaimJustification__NameAssignment_1");
			builder.put(grammarAccess.getClaimJustificationAccess().getValAssignment_3(), "rule__ClaimJustification__ValAssignment_3");
			builder.put(grammarAccess.getClaimAssumptionAccess().getNameAssignment_1(), "rule__ClaimAssumption__NameAssignment_1");
			builder.put(grammarAccess.getClaimAssumptionAccess().getExprAssignment_3(), "rule__ClaimAssumption__ExprAssignment_3");
			builder.put(grammarAccess.getClaimStrategyAccess().getNameAssignment_1(), "rule__ClaimStrategy__NameAssignment_1");
			builder.put(grammarAccess.getClaimStrategyAccess().getValAssignment_3(), "rule__ClaimStrategy__ValAssignment_3");
			builder.put(grammarAccess.getClaimTextAccess().getStrAssignment_0_1(), "rule__ClaimText__StrAssignment_0_1");
			builder.put(grammarAccess.getClaimTextAccess().getArgAssignment_1_1(), "rule__ClaimText__ArgAssignment_1_1");
			builder.put(grammarAccess.getClaimTextAccess().getUnitAssignment_1_2_1(), "rule__ClaimText__UnitAssignment_1_2_1");
			builder.put(grammarAccess.getImpliesExprAccess().getOpAssignment_1_0_0_1(), "rule__ImpliesExpr__OpAssignment_1_0_0_1");
			builder.put(grammarAccess.getImpliesExprAccess().getRightAssignment_1_1(), "rule__ImpliesExpr__RightAssignment_1_1");
			builder.put(grammarAccess.getOrExprAccess().getOpAssignment_1_0_0_1_0(), "rule__OrExpr__OpAssignment_1_0_0_1_0");
			builder.put(grammarAccess.getOrExprAccess().getOpAssignment_1_0_0_1_1(), "rule__OrExpr__OpAssignment_1_0_0_1_1");
			builder.put(grammarAccess.getOrExprAccess().getRightAssignment_1_1(), "rule__OrExpr__RightAssignment_1_1");
			builder.put(grammarAccess.getAndExprAccess().getOpAssignment_1_0_0_1_0(), "rule__AndExpr__OpAssignment_1_0_0_1_0");
			builder.put(grammarAccess.getAndExprAccess().getOpAssignment_1_0_0_1_1(), "rule__AndExpr__OpAssignment_1_0_0_1_1");
			builder.put(grammarAccess.getAndExprAccess().getRightAssignment_1_1(), "rule__AndExpr__RightAssignment_1_1");
			builder.put(grammarAccess.getInstanceOfExprAccess().getTypeAssignment_1_1(), "rule__InstanceOfExpr__TypeAssignment_1_1");
			builder.put(grammarAccess.getRelationalExprAccess().getOpAssignment_1_0_0_1(), "rule__RelationalExpr__OpAssignment_1_0_0_1");
			builder.put(grammarAccess.getRelationalExprAccess().getRightAssignment_1_1(), "rule__RelationalExpr__RightAssignment_1_1");
			builder.put(grammarAccess.getPlusExprAccess().getOpAssignment_1_0_0_1(), "rule__PlusExpr__OpAssignment_1_0_0_1");
			builder.put(grammarAccess.getPlusExprAccess().getRightAssignment_1_1(), "rule__PlusExpr__RightAssignment_1_1");
			builder.put(grammarAccess.getTimesExprAccess().getOpAssignment_1_0_0_1(), "rule__TimesExpr__OpAssignment_1_0_0_1");
			builder.put(grammarAccess.getTimesExprAccess().getRightAssignment_1_1(), "rule__TimesExpr__RightAssignment_1_1");
			builder.put(grammarAccess.getExpExprAccess().getOpAssignment_1_0_0_1(), "rule__ExpExpr__OpAssignment_1_0_0_1");
			builder.put(grammarAccess.getExpExprAccess().getRightAssignment_1_1(), "rule__ExpExpr__RightAssignment_1_1");
			builder.put(grammarAccess.getPrefixExprAccess().getOpAssignment_0_1(), "rule__PrefixExpr__OpAssignment_0_1");
			builder.put(grammarAccess.getPrefixExprAccess().getExprAssignment_0_2(), "rule__PrefixExpr__ExprAssignment_0_2");
			builder.put(grammarAccess.getPrefixExprAccess().getTypeAssignment_1_2(), "rule__PrefixExpr__TypeAssignment_1_2");
			builder.put(grammarAccess.getPrefixExprAccess().getExprAssignment_1_4(), "rule__PrefixExpr__ExprAssignment_1_4");
			builder.put(grammarAccess.getAtomicExprAccess().getIdAssignment_0_1(), "rule__AtomicExpr__IdAssignment_0_1");
			builder.put(grammarAccess.getAtomicExprAccess().getSubAssignment_1_2_1(), "rule__AtomicExpr__SubAssignment_1_2_1");
			builder.put(grammarAccess.getAtomicExprAccess().getValAssignment_2_2_0(), "rule__AtomicExpr__ValAssignment_2_2_0");
			builder.put(grammarAccess.getAtomicExprAccess().getFailmsgAssignment_2_2_1_1(), "rule__AtomicExpr__FailmsgAssignment_2_2_1_1");
			builder.put(grammarAccess.getAtomicExprAccess().getValAssignment_3_1(), "rule__AtomicExpr__ValAssignment_3_1");
			builder.put(grammarAccess.getAtomicExprAccess().getValAssignment_4_1(), "rule__AtomicExpr__ValAssignment_4_1");
			builder.put(grammarAccess.getAtomicExprAccess().getValAssignment_5_1(), "rule__AtomicExpr__ValAssignment_5_1");
			builder.put(grammarAccess.getAtomicExprAccess().getValAssignment_6_1(), "rule__AtomicExpr__ValAssignment_6_1");
			builder.put(grammarAccess.getAtomicExprAccess().getCondAssignment_7_2(), "rule__AtomicExpr__CondAssignment_7_2");
			builder.put(grammarAccess.getAtomicExprAccess().getThenAssignment_7_4(), "rule__AtomicExpr__ThenAssignment_7_4");
			builder.put(grammarAccess.getAtomicExprAccess().getElseAssignment_7_6(), "rule__AtomicExpr__ElseAssignment_7_6");
			builder.put(grammarAccess.getAtomicExprAccess().getQuantAssignment_8_1(), "rule__AtomicExpr__QuantAssignment_8_1");
			builder.put(grammarAccess.getAtomicExprAccess().getArgsAssignment_8_2_1(), "rule__AtomicExpr__ArgsAssignment_8_2_1");
			builder.put(grammarAccess.getAtomicExprAccess().getExprAssignment_8_4(), "rule__AtomicExpr__ExprAssignment_8_4");
			builder.put(grammarAccess.getAtomicExprAccess().getLibNameAssignment_9_0_1(), "rule__AtomicExpr__LibNameAssignment_9_0_1");
			builder.put(grammarAccess.getAtomicExprAccess().getFnNameAssignment_9_0_3(), "rule__AtomicExpr__FnNameAssignment_9_0_3");
			builder.put(grammarAccess.getAtomicExprAccess().getArgsAssignment_9_0_5_0(), "rule__AtomicExpr__ArgsAssignment_9_0_5_0");
			builder.put(grammarAccess.getAtomicExprAccess().getArgsAssignment_9_0_5_1_1(), "rule__AtomicExpr__ArgsAssignment_9_0_5_1_1");
			builder.put(grammarAccess.getAtomicExprAccess().getFnAssignment_10_1(), "rule__AtomicExpr__FnAssignment_10_1");
			builder.put(grammarAccess.getAtomicExprAccess().getArgsAssignment_10_3_0(), "rule__AtomicExpr__ArgsAssignment_10_3_0");
			builder.put(grammarAccess.getAtomicExprAccess().getArgsAssignment_10_3_1_1(), "rule__AtomicExpr__ArgsAssignment_10_3_1_1");
			builder.put(grammarAccess.getAtomicExprAccess().getFnAssignment_11_1(), "rule__AtomicExpr__FnAssignment_11_1");
			builder.put(grammarAccess.getAtomicExprAccess().getArgsAssignment_11_3_0(), "rule__AtomicExpr__ArgsAssignment_11_3_0");
			builder.put(grammarAccess.getAtomicExprAccess().getArgsAssignment_11_3_1_1(), "rule__AtomicExpr__ArgsAssignment_11_3_1_1");
			builder.put(grammarAccess.getAtomicExprAccess().getLintStmtAssignment_12_1(), "rule__AtomicExpr__LintStmtAssignment_12_1");
			builder.put(grammarAccess.getAtomicExprAccess().getArgsAssignment_13_2_0_2_1(), "rule__AtomicExpr__ArgsAssignment_13_2_0_2_1");
			builder.put(grammarAccess.getAtomicExprAccess().getFilterAssignment_13_2_0_3_1(), "rule__AtomicExpr__FilterAssignment_13_2_0_3_1");
			builder.put(grammarAccess.getAtomicExprAccess().getExprsAssignment_13_2_1_1_1(), "rule__AtomicExpr__ExprsAssignment_13_2_1_1_1");
			builder.put(grammarAccess.getAtomicExprAccess().getArgsAssignment_14_2_0_2_1(), "rule__AtomicExpr__ArgsAssignment_14_2_0_2_1");
			builder.put(grammarAccess.getAtomicExprAccess().getFilterAssignment_14_2_0_3_1(), "rule__AtomicExpr__FilterAssignment_14_2_0_3_1");
			builder.put(grammarAccess.getAtomicExprAccess().getExprsAssignment_14_2_1_1_1(), "rule__AtomicExpr__ExprsAssignment_14_2_1_1_1");
			builder.put(grammarAccess.getAtomicExprAccess().getBindingAssignment_17_2(), "rule__AtomicExpr__BindingAssignment_17_2");
			builder.put(grammarAccess.getAtomicExprAccess().getExprAssignment_17_4(), "rule__AtomicExpr__ExprAssignment_17_4");
			builder.put(grammarAccess.getAtomicExprAccess().getNameAssignment_20_2(), "rule__AtomicExpr__NameAssignment_20_2");
			builder.put(grammarAccess.getAtomicExprAccess().getValAssignment_20_4(), "rule__AtomicExpr__ValAssignment_20_4");
			builder.put(grammarAccess.getLetBindingAccess().getNameAssignment_0(), "rule__LetBinding__NameAssignment_0");
			builder.put(grammarAccess.getLetBindingAccess().getTypeAssignment_2(), "rule__LetBinding__TypeAssignment_2");
			builder.put(grammarAccess.getLetBindingAccess().getExprAssignment_4(), "rule__LetBinding__ExprAssignment_4");
			builder.put(grammarAccess.getRealTermAccess().getValueAssignment_0(), "rule__RealTerm__ValueAssignment_0");
			builder.put(grammarAccess.getRealTermAccess().getUnitAssignment_1(), "rule__RealTerm__UnitAssignment_1");
			builder.put(grammarAccess.getIntegerTermAccess().getValueAssignment_0(), "rule__IntegerTerm__ValueAssignment_0");
			builder.put(grammarAccess.getIntegerTermAccess().getUnitAssignment_1(), "rule__IntegerTerm__UnitAssignment_1");
			builder.put(grammarAccess.getResoluteSubclauseAccess().getAnalysesAssignment_1(), "rule__ResoluteSubclause__AnalysesAssignment_1");
			builder.put(grammarAccess.getNestedDotIDAccess().getBaseAssignment_0(), "rule__NestedDotID__BaseAssignment_0");
			builder.put(grammarAccess.getNestedDotIDAccess().getSubAssignment_1_1(), "rule__NestedDotID__SubAssignment_1_1");
			builder.put(grammarAccess.getLintStatementAccess().getExprAssignment_0_2(), "rule__LintStatement__ExprAssignment_0_2");
			builder.put(grammarAccess.getLintStatementAccess().getExprAssignment_1_2(), "rule__LintStatement__ExprAssignment_1_2");
			builder.put(grammarAccess.getLintStatementAccess().getExprAssignment_2_2(), "rule__LintStatement__ExprAssignment_2_2");
			builder.put(grammarAccess.getRulesetAccess().getNameAssignment_1(), "rule__Ruleset__NameAssignment_1");
			builder.put(grammarAccess.getRulesetAccess().getBodyAssignment_3(), "rule__Ruleset__BodyAssignment_3");
			builder.put(grammarAccess.getRulesetBodyAccess().getLintStatementsAssignment_1(), "rule__RulesetBody__LintStatementsAssignment_1");
			builder.put(grammarAccess.getAnalysisStatementAccess().getTagAssignment_0_1(), "rule__AnalysisStatement__TagAssignment_0_1");
			builder.put(grammarAccess.getAnalysisStatementAccess().getExprAssignment_0_2(), "rule__AnalysisStatement__ExprAssignment_0_2");
			builder.put(grammarAccess.getAnalysisStatementAccess().getExprAssignment_1_2(), "rule__AnalysisStatement__ExprAssignment_1_2");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getPropertyAssignment_0(), "rule__ContainedPropertyAssociation__PropertyAssignment_0");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getAppendAssignment_1_1(), "rule__ContainedPropertyAssociation__AppendAssignment_1_1");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getConstantAssignment_2(), "rule__ContainedPropertyAssociation__ConstantAssignment_2");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getOwnedValueAssignment_3_0(), "rule__ContainedPropertyAssociation__OwnedValueAssignment_3_0");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getOwnedValueAssignment_3_1_1(), "rule__ContainedPropertyAssociation__OwnedValueAssignment_3_1_1");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getAppliesToAssignment_4_1(), "rule__ContainedPropertyAssociation__AppliesToAssignment_4_1");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getAppliesToAssignment_4_2_1(), "rule__ContainedPropertyAssociation__AppliesToAssignment_4_2_1");
			builder.put(grammarAccess.getContainedPropertyAssociationAccess().getInBindingAssignment_5_2(), "rule__ContainedPropertyAssociation__InBindingAssignment_5_2");
			builder.put(grammarAccess.getPropertyAssociationAccess().getPropertyAssignment_0(), "rule__PropertyAssociation__PropertyAssignment_0");
			builder.put(grammarAccess.getPropertyAssociationAccess().getAppendAssignment_1_1(), "rule__PropertyAssociation__AppendAssignment_1_1");
			builder.put(grammarAccess.getPropertyAssociationAccess().getConstantAssignment_2(), "rule__PropertyAssociation__ConstantAssignment_2");
			builder.put(grammarAccess.getPropertyAssociationAccess().getOwnedValueAssignment_3_0(), "rule__PropertyAssociation__OwnedValueAssignment_3_0");
			builder.put(grammarAccess.getPropertyAssociationAccess().getOwnedValueAssignment_3_1_1(), "rule__PropertyAssociation__OwnedValueAssignment_3_1_1");
			builder.put(grammarAccess.getPropertyAssociationAccess().getInBindingAssignment_4_2(), "rule__PropertyAssociation__InBindingAssignment_4_2");
			builder.put(grammarAccess.getBasicPropertyAssociationAccess().getPropertyAssignment_0(), "rule__BasicPropertyAssociation__PropertyAssignment_0");
			builder.put(grammarAccess.getBasicPropertyAssociationAccess().getOwnedValueAssignment_2(), "rule__BasicPropertyAssociation__OwnedValueAssignment_2");
			builder.put(grammarAccess.getContainmentPathAccess().getPathAssignment(), "rule__ContainmentPath__PathAssignment");
			builder.put(grammarAccess.getModalPropertyValueAccess().getOwnedValueAssignment_0(), "rule__ModalPropertyValue__OwnedValueAssignment_0");
			builder.put(grammarAccess.getModalPropertyValueAccess().getInModeAssignment_3(), "rule__ModalPropertyValue__InModeAssignment_3");
			builder.put(grammarAccess.getModalPropertyValueAccess().getInModeAssignment_4_1(), "rule__ModalPropertyValue__InModeAssignment_4_1");
			builder.put(grammarAccess.getOptionalModalPropertyValueAccess().getOwnedValueAssignment_0(), "rule__OptionalModalPropertyValue__OwnedValueAssignment_0");
			builder.put(grammarAccess.getOptionalModalPropertyValueAccess().getInModeAssignment_1_2(), "rule__OptionalModalPropertyValue__InModeAssignment_1_2");
			builder.put(grammarAccess.getOptionalModalPropertyValueAccess().getInModeAssignment_1_3_1(), "rule__OptionalModalPropertyValue__InModeAssignment_1_3_1");
			builder.put(grammarAccess.getPropertyValueAccess().getOwnedValueAssignment(), "rule__PropertyValue__OwnedValueAssignment");
			builder.put(grammarAccess.getLiteralorReferenceTermAccess().getNamedValueAssignment(), "rule__LiteralorReferenceTerm__NamedValueAssignment");
			builder.put(grammarAccess.getBooleanLiteralAccess().getValueAssignment_1_0(), "rule__BooleanLiteral__ValueAssignment_1_0");
			builder.put(grammarAccess.getConstantValueAccess().getNamedValueAssignment(), "rule__ConstantValue__NamedValueAssignment");
			builder.put(grammarAccess.getReferenceTermAccess().getPathAssignment_2(), "rule__ReferenceTerm__PathAssignment_2");
			builder.put(grammarAccess.getRecordTermAccess().getOwnedFieldValueAssignment_1(), "rule__RecordTerm__OwnedFieldValueAssignment_1");
			builder.put(grammarAccess.getOldRecordTermAccess().getOwnedFieldValueAssignment_1(), "rule__OldRecordTerm__OwnedFieldValueAssignment_1");
			builder.put(grammarAccess.getComputedTermAccess().getFunctionAssignment_2(), "rule__ComputedTerm__FunctionAssignment_2");
			builder.put(grammarAccess.getComponentClassifierTermAccess().getClassifierAssignment_2(), "rule__ComponentClassifierTerm__ClassifierAssignment_2");
			builder.put(grammarAccess.getListTermAccess().getOwnedListElementAssignment_2_0(), "rule__ListTerm__OwnedListElementAssignment_2_0");
			builder.put(grammarAccess.getListTermAccess().getOwnedListElementAssignment_2_1_1(), "rule__ListTerm__OwnedListElementAssignment_2_1_1");
			builder.put(grammarAccess.getFieldPropertyAssociationAccess().getPropertyAssignment_0(), "rule__FieldPropertyAssociation__PropertyAssignment_0");
			builder.put(grammarAccess.getFieldPropertyAssociationAccess().getOwnedValueAssignment_2(), "rule__FieldPropertyAssociation__OwnedValueAssignment_2");
			builder.put(grammarAccess.getContainmentPathElementAccess().getNamedElementAssignment_0_0(), "rule__ContainmentPathElement__NamedElementAssignment_0_0");
			builder.put(grammarAccess.getContainmentPathElementAccess().getArrayRangeAssignment_0_1(), "rule__ContainmentPathElement__ArrayRangeAssignment_0_1");
			builder.put(grammarAccess.getContainmentPathElementAccess().getPathAssignment_1_1(), "rule__ContainmentPathElement__PathAssignment_1_1");
			builder.put(grammarAccess.getStringTermAccess().getValueAssignment(), "rule__StringTerm__ValueAssignment");
			builder.put(grammarAccess.getArrayRangeAccess().getLowerBoundAssignment_2(), "rule__ArrayRange__LowerBoundAssignment_2");
			builder.put(grammarAccess.getArrayRangeAccess().getUpperBoundAssignment_3_1(), "rule__ArrayRange__UpperBoundAssignment_3_1");
			builder.put(grammarAccess.getSignedConstantAccess().getOpAssignment_0(), "rule__SignedConstant__OpAssignment_0");
			builder.put(grammarAccess.getSignedConstantAccess().getOwnedPropertyExpressionAssignment_1(), "rule__SignedConstant__OwnedPropertyExpressionAssignment_1");
			builder.put(grammarAccess.getNumericRangeTermAccess().getMinimumAssignment_0(), "rule__NumericRangeTerm__MinimumAssignment_0");
			builder.put(grammarAccess.getNumericRangeTermAccess().getMaximumAssignment_2(), "rule__NumericRangeTerm__MaximumAssignment_2");
			builder.put(grammarAccess.getNumericRangeTermAccess().getDeltaAssignment_3_1(), "rule__NumericRangeTerm__DeltaAssignment_3_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private ResoluteGrammarAccess grammarAccess;

	@Override
	protected InternalResoluteParser createParser() {
		InternalResoluteParser result = new InternalResoluteParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_SL_COMMENT" };
	}

	public ResoluteGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ResoluteGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
