# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Push and publish release to GitHub

on:
  push:
    tags:
      - '*'

jobs:

  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Install Dependencies
      run: sudo apt-get install -y pandoc
    - name: Compile and Test Maven Project
      run: mvn clean verify

  publish:
    runs-on: ubuntu-latest
    needs: verify
    permissions:
        contents: read
        packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set Up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Install Dependencies
      run: sudo apt-get install -y pandoc
    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'GH_Actions@users.noreply.github.com'
    - name: Deploy Maven Project to Github Pages
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
      run: >
        mvn deploy
        -Pupdate-release-site
        -Dgithub-update-repo=https://x-access-token:${{ secrets.ACTION_TOKEN }}@github.com/loonwerks/Resolute-Updates
    - name: Upload p2 repo artifact
      uses: actions/upload-artifact@v3
      with:
        name: p2-artifact
        path: ${{ github.workspace }}/com.rockwellcollins.atc.resolute.site/target/repository/

  release:
    runs-on: ubuntu-latest
    needs: publish
    permissions:
      contents: write
    steps:
    - name: Get version number
      uses: jungwinter/split@v2
      id: version_number
      with:
        msg: ${{ github.ref_name }}
        separator: '-'
    - name: Get current date
      id: date
      run: echo "date=$(date +'%B %e, %Y')" >> $GITHUB_OUTPUT
    - name: Download p2 repo artifact
      uses: actions/download-artifact@v3
      with:
        name: p2-artifact
    - name: Zip Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'com.rockwellcollins.atc.resolute.repository-${{ steps.version_number.outputs._0 }}.zip'
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        name: Release ${{ steps.version_number.outputs._0 }}
        artifacts: 'com.rockwellcollins.atc.resolute.repository-${{ steps.version_number.outputs._0 }}.zip'
        body: |
              # Version ${{ steps.version_number.outputs._0 }}

              -   GIT tag: ${{ github.ref_name }}
              -   Release date: ${{ steps.date.outputs.date }}
              -   OSATE version: 2.12.0
              -   Eclipse base version: 2022-06
              -   Java version: Java 17
              -   Eclipse Update-Site: https://loonwerks.github.io/Resolute-Updates/releases/${{ steps.version_number.outputs._0 }}
        generateReleaseNotes: true