# This workflow will build a package using Maven and then publish it to GitHub packages when a snapshot is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Push snapshot to Github Pages

on:
  workflow_run:
    workflows: [Build and Test Project]
    types: [completed]
    branches: [main]

jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    steps:
    - uses: actions/checkout@v3
    - name: Set Up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Install Dependencies
      run: sudo apt-get install -y pandoc
    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'GitHub_Actions@users.noreply.github.com'
    - name: Deploy Maven Project to Github Pages
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
      run: >
        mvn deploy
        -Pupdate-snapshot-site
        -Dgithub-update-repo=https://x-access-token:${{ secrets.ACTION_TOKEN }}@github.com/aaurandt/Resolute_test-Updates