name: Push snapshot to Github Pages

on:
  workflow_run:
    workflows: [Build and Test Project]
    types: [completed]
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    steps:
    - uses: actions/checkout@v3
    - name: Set Up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Install Dependencies
      run: sudo apt-get install -y pandoc
    - name: Build snapshot
      run: mvn verify -Pbuild-snapshot
    - name: Upload p2 repo artifact
      uses: actions/upload-artifact@v3
      with:
        name: p2-artifact
        path: ${{ github.workspace }}/com.rockwellcollins.atc.resolute.site/target/repository/

  publish:
    runs-on: ubuntu-latest
    needs: verify
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Install Eclipse
      run: sudo snap install --classic eclipse
    - name: Checkout current update site
      uses: actions/checkout@v3
      with:
        repository: loonwerks/Resolute-Updates
        path: Resolute-Updates
        token: ${{ secrets.ACTION_TOKEN }}
        persist-credentials: true
    - name: Download p2 repo artifact
      uses: actions/download-artifact@v3
      with:
        name: p2-artifact
        path: ${{ github.workspace }}/p2-artifact
    - name: Parse version number
      run: echo "SNAPSHOT_VERSION=$(ls ${{ github.workspace }}/p2-artifact/plugins/com.rockwellcollins.atc.resolute_*.jar | grep -o "[0-9]\\+\\.[0-9]\\+\\.[0-9]\\+\\.[0-9]\\{12\\}")" >> $GITHUB_ENV
    - name: Rename p2-artifact and move to snapshot directory
      run: |
          mv ${{ github.workspace }}/p2-artifact ${{ github.workspace }}/${{ env.SNAPSHOT_VERSION }}
          mv ${{ github.workspace }}/${{ env.SNAPSHOT_VERSION }} ${{ github.workspace }}/Resolute-Updates/snapshots
    - name: Build with Ant
      run: java -jar /snap/eclipse/*/plugins/org.eclipse.equinox.launcher_*.jar -application org.eclipse.ant.core.antRunner -buildfile  ${{ github.workspace }}/com.rockwellcollins.atc.resolute.site/packaging-p2composite.ant p2.composite.add.snapshot -Dcomposite.base.dir=${{ github.workspace }}/Resolute-Updates -Dfull.version=${{ env.SNAPSHOT_VERSION }}
    - name: Push new snapshot to Resolute-Updates
      run: | 
          cd Resolute-Updates
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'GH_Actions@users.noreply.github.com'
          git add .
          git commit -m 'Snapshot ${{ env.SNAPSHOT_VERSION }}'
          git push
